# ConfigMap used as param for operator-subscription-matches-cluster policy.
# List of subscription names allowed for this cluster (OKE: only OKE).
# Add more validSubscription.N entries to allow more products, e.g. "Red Hat Trusted Profile Analyzer".
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-subscription-type
  namespace: operator-subscription
data:
  validSubscription.0: "OpenShift Kubernetes Engine"
