# ConfigMap used as param for operator-subscription-matches-cluster policy.
# Use this when the cluster is subscribed as OpenShift Kubernetes Engine (OKE).
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-subscription-type
  namespace: operator-subscription
data:
  subscriptionType: "OpenShift Kubernetes Engine"
